version: 2

jobs:
  python-pip: &pip-template
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            python -m venv $HOME/venv_circleci
            . $HOME/venv_circleci/bin/activate
            pip install numpy numba pytest flake8 docutils
      - run:
          name: Check setup.py
          command: |
            . $HOME/venv_circleci/bin/activate
            python setup.py check -m -r -s  
      - run:
          name: Run tests
          command: |
            . $HOME/venv_circleci/bin/activate
            pip list
            pytest tests
      - run:
          name: Run linter
          command: |
            . $HOME/venv_circleci/bin/activate
            flake8 .
      - store_artifacts:
          path: artifacts

  python-conda: &conda-template
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      #- restore_cache:
      #    keys:
      #      - conda-v1-{{ checksum "???" }}
      - run:
          name: Install miniconda
          command: |
            wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            chmod +x miniconda.sh
            ./miniconda.sh -b -p $HOME/miniconda
            . $HOME/miniconda/etc/profile.d/conda.sh
            conda create -n circleci --yes python=$PYTHON_VERSION \
              numpy numba pytest flake8 docutils
      #- save_cache:
      #    key: conda-v1-{{ checksum "???" }}
      #    paths:
      #      - /home/circleci/miniconda/
      - run:
          name: Check setup.py
          command: |
            . $HOME/miniconda/etc/profile.d/conda.sh
            conda activate circleci
            python setup.py check -m -r -s  
      - run:
          name: Run tests
          command: |
            . $HOME/miniconda/etc/profile.d/conda.sh
            conda activate circleci
            conda list
            pytest tests
      - run:
          name: Run linter
          command: |
            . $HOME/miniconda/etc/profile.d/conda.sh
            conda activate circleci
            flake8 .
      - store_artifacts:
          path: artifacts
          
  python-3.6-pip:
    <<: *pip-template
    docker:
      - image: circleci/python:3.6

  python-3.7-pip:
    <<: *pip-template
    docker:
      - image: circleci/python:3.7

  python-3.6-conda:
    <<: *conda-template
    docker:
      - image: circleci/python:3.6
        environment:
          PYTHON_VERSION: 3.6
          
  python-3.7-conda:
    <<: *conda-template
    docker:
      - image: circleci/python:3.6
        environment:
          PYTHON_VERSION: 3.7

workflows:
  version: 2
  build:
    jobs:
      - python-3.6-pip
      - python-3.6-conda
      #- python-3-7-conda:
      #    requires:
      #      - python-3.6-pip
      #    filters:
      #      branches:
      #        only:
      #          - master
      #          - /release_.*/
      #          - /conda_build_.*/
